# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AgoraRNQuickstart' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AgoraRNQuickstart

  target 'AgoraRNQuickstart-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AgoraRNQuickstartTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


